{{- if .Values.networkPolicy.enabled }}
---
# Default deny all ingress traffic
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "aurelius.fullname" . }}-default-deny
  labels:
    {{- include "aurelius.labels" . | nindent 4 }}
spec:
  podSelector: {}
  policyTypes:
  - Ingress
---
# Allow ingress from ingress controller
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "aurelius.fullname" . }}-allow-ingress
  labels:
    {{- include "aurelius.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "aurelius.name" . }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
    ports:
    - protocol: TCP
      port: 8000
    - protocol: TCP
      port: 3000
---
# Allow internal service communication
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "aurelius.fullname" . }}-allow-internal
  labels:
    {{- include "aurelius.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "aurelius.name" . }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: {{ include "aurelius.name" . }}
    ports:
    - protocol: TCP
      port: 8000
    - protocol: TCP
      port: 50051
    - protocol: TCP
      port: 50052
    - protocol: TCP
      port: 50053
    - protocol: TCP
      port: 50054
    - protocol: TCP
      port: 50055
---
# Allow Prometheus to scrape metrics
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "aurelius.fullname" . }}-allow-prometheus
  labels:
    {{- include "aurelius.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "aurelius.name" . }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: monitoring
    ports:
    - protocol: TCP
      port: 9090
    - protocol: TCP
      port: 8001
---
# Egress rules
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "aurelius.fullname" . }}-egress
  labels:
    {{- include "aurelius.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "aurelius.name" . }}
  policyTypes:
  - Egress
  egress:
  # Allow DNS
  {{- range .Values.networkPolicy.egressRules }}
  - to:
    {{- toYaml .to | nindent 6 }}
    ports:
    {{- toYaml .ports | nindent 6 }}
  {{- end }}
  # Allow access to PostgreSQL
  - to:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: postgresql
    ports:
    - protocol: TCP
      port: 5432
  # Allow access to Redis
  - to:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: redis
    ports:
    - protocol: TCP
      port: 6379
  # Allow access to MinIO
  - to:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: minio
    ports:
    - protocol: TCP
      port: 9000
  # Allow access to Keycloak
  - to:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: keycloak
    ports:
    - protocol: TCP
      port: 8080
  # Allow access to Jaeger
  - to:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: jaeger
    ports:
    - protocol: TCP
      port: 4317
    - protocol: TCP
      port: 14250
{{- end }}
