{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aurelius.fullname" . }}-secrets
  labels:
    {{- include "aurelius.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets.data }}
  {{ $key }}: {{ $value }}
  {{- end }}
---
# NOTE: This is a basic secret template for development/testing
# In production, use one of the following instead:
# 1. Sealed Secrets (bitnami-labs/sealed-secrets)
# 2. External Secrets Operator (external-secrets/external-secrets)
# 3. HashiCorp Vault
# 4. AWS Secrets Manager / Azure Key Vault / GCP Secret Manager
#
# Example with External Secrets Operator:
# ---
# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: {{ include "aurelius.fullname" . }}-secrets
# spec:
#   refreshInterval: 1h
#   secretStoreRef:
#     name: vault-backend
#     kind: SecretStore
#   target:
#     name: {{ include "aurelius.fullname" . }}-secrets
#     creationPolicy: Owner
#   data:
#   - secretKey: database-url
#     remoteRef:
#       key: aurelius/database-url
#   - secretKey: redis-url
#     remoteRef:
#       key: aurelius/redis-url
#   # ... etc
{{- end }}
