{{- if .Values.prometheus.enabled }}
---
# Gateway ServiceMonitor
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "aurelius.fullname" . }}-gateway
  labels:
    {{- include "aurelius.gateway.labels" . | nindent 4 }}
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      {{- include "aurelius.gateway.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: metrics
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
---
# ML Service ServiceMonitor
{{- if .Values.mlService.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "aurelius.fullname" . }}-ml-service
  labels:
    {{- include "aurelius.ml.labels" . | nindent 4 }}
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      {{- include "aurelius.ml.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: metrics
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
{{- end }}
---
# PrometheusRule for alerts
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "aurelius.fullname" . }}-alerts
  labels:
    {{- include "aurelius.labels" . | nindent 4 }}
    prometheus: kube-prometheus
spec:
  groups:
  - name: aurelius
    interval: 30s
    rules:
    # High error rate
    - alert: HighErrorRate
      expr: |
        sum(rate(http_requests_total{status=~"5.."}[5m])) by (service)
        /
        sum(rate(http_requests_total[5m])) by (service)
        > 0.05
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High error rate detected"
        description: "Service {{ $labels.service }} has error rate above 5% (current: {{ $value | humanizePercentage }})"
    
    # High latency
    - alert: HighLatency
      expr: |
        histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket[5m])) by (service, le))
        > 5
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High latency detected"
        description: "Service {{ $labels.service }} has P99 latency above 5s (current: {{ $value }}s)"
    
    # Pod not ready
    - alert: PodNotReady
      expr: |
        kube_pod_status_ready{condition="false", namespace="{{ .Release.Namespace }}"}
        == 1
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "Pod not ready"
        description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} is not ready"
    
    # High memory usage
    - alert: HighMemoryUsage
      expr: |
        container_memory_usage_bytes{namespace="{{ .Release.Namespace }}"}
        /
        container_spec_memory_limit_bytes{namespace="{{ .Release.Namespace }}"}
        > 0.9
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High memory usage"
        description: "Container {{ $labels.container }} in pod {{ $labels.pod }} is using >90% of memory limit"
    
    # GPU not available
    {{- if .Values.mlService.enabled }}
    - alert: GPUNotAvailable
      expr: |
        DCGM_FI_DEV_GPU_UTIL{namespace="{{ .Release.Namespace }}"}
        == 0
      for: 10m
      labels:
        severity: critical
      annotations:
        summary: "GPU not available"
        description: "GPU {{ $labels.gpu }} is not being utilized for more than 10 minutes"
    {{- end }}
    
    # Tenant quota exceeded
    - alert: TenantQuotaExceeded
      expr: |
        tenant_quota_usage_percent{namespace="{{ .Release.Namespace }}"}
        > 90
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "Tenant quota exceeded"
        description: "Tenant {{ $labels.tenant_id }} has exceeded 90% of {{ $labels.resource }} quota"
    
    # Database connection issues
    - alert: DatabaseConnectionPoolExhausted
      expr: |
        pg_stat_activity_count{namespace="{{ .Release.Namespace }}"}
        /
        pg_settings_max_connections
        > 0.8
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "Database connection pool near exhaustion"
        description: "PostgreSQL connection pool is >80% utilized"
{{- end }}
